### ISSUE TITLE
Random Crashes on death

### ISSUE THREAD

**Issue by TristonWasik** [genDevo/1.16-Stardew-Armory#10]
I am getting crashes randomly when a player dies on my server. The server is the terralux: a new experience modpack. How a player dies doesnt seem to matter as it's happened from zombie deaths in overworld, ghast deaths in nether, foxhound deaths in nether, and tnt (below screenshot).

Screenshot of exception:
![image](https://user-images.githubusercontent.com/32952542/168534512-d4c05630-99bb-4a2d-96ca-aa670d29c6f2.png)

**Comment by genDevo** [comment]
Fixed in the [newest release](https://github.com/genDevo/Stardew-Armory/releases/tag/v1.18Forge-1.3.10).
