### ISSUE TITLE
Silver Saber damage too high?

### ISSUE THREAD

**Issue by dieflemm** [genDevo/1.16-Stardew-Armory#4]
I've tested your mod and looked through the items provided. I noticed that the Silver Sabre has a damage value off 80.
It seems off compared to the other swords.
Tested it on mobs and it one-shots everything. Seems way too OP.
Can you check if this value is right?

edit: using 1.18.1 Version, StardewArmory-1.18.1-1.2.0.jar

![silversword 80dmg](https://user-images.githubusercontent.com/26855879/147249456-ef33ffb7-86dc-47bf-a06e-a77afabb0a6d.png)

**Comment by genDevo** [comment]
It was intended as a debugging item since it was unobtainable, upcoming update should rectify this.
