### ISSUE TITLE
Ticking entity server crash

### ISSUE THREAD

**Issue by HueboWasTaken** [genDevo/1.16-Stardew-Armory#5]
not sure if stardew armory is causing this but it's mentioned in the crash log, server crashes as soon as this entity is loaded

https://pastebin.com/Ey0PPUTS

**Comment by genDevo** [comment]
Fixed in [https://github.com/genDevo/Stardew-Armory/commit/e5622484f5ac7bb2febb1a829c2e51a66b1eefa3](url)
