### ISSUE TITLE
1.18.1 Server Crash

### ISSUE THREAD

**Issue by Darkfiend009** [genDevo/1.16-Stardew-Armory#6]
Forge: 39.0.63
Stardew Armory: 1.3.3

Server crashes when player with Lucky Strike enchantment connects to the server. I edited the playerdata and remove the enchantment from the player's weapon and they were able to connect.

Crash Report: https://pastebin.com/Dzi6s5Bd

**Comment by genDevo** [comment]
Fixed in: [https://github.com/genDevo/Stardew-Armory/releases/tag/v1.18Forge-1.3.4](https://github.com/genDevo/Stardew-Armory/releases/tag/v1.18Forge-1.3.4)
