### ISSUE TITLE
Exception Ticking World (MC 1.18.2, SDA 1.3.7)

### ISSUE THREAD

**Issue by Anaerin** [genDevo/1.16-Stardew-Armory#9]
Something in StarDew Armory is causing a server crash with casting exceptions. Crashlog here:

[crash-2022-04-30_09.17.42-server.txt](https://github.com/genDevo/Stardew-Armory/files/8597230/crash-2022-04-30_09.17.42-server.txt)

**Comment by genDevo** [comment]
Addressed [here](https://github.com/genDevo/Stardew-Armory/commit/44828a74980b0decfd418240d5880861e07bb081)
